[workspace]
resolver = "3"
members = ["crates/bevy_widgetry", "crates/core", "crates/button", "crates/combo_box"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
bevy = {
    version = "=0.19.1",
    default-features = false,
    features = ["ui"]
}
rstest = "0.26.1"
