[workspace]
resolver = "3"
members = [
    "crates/log",
    "crates/asset",
    "crates/bevy_widgetry",
    "crates/core",
    "crates/button",
    "crates/combo_box",
    "crates/text_field",
    "crates/test_utils",
    "crates/window",
    "gallery",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
bevy = {
    version = "=0.19.1",
    default-features = false,
    features = ["ui"]
}
wgpu = { version = "=29.0.4", default-features = false, features = ["dx12"] }
rstest = "0.26.1"
resvg = "0.48.1"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["time"] }
time = { version = "0.3.55", features = ["formatting", "macros", "local-offset"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "deny"
type_complexity = "allow"
too_many_arguments = "allow"

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = 0
