[package]
name = "bevy_widgetry_tree"
version.workspace = true
edition.workspace = true

[dependencies]
bevy_widgetry_theme = { path = "../theme" }
bevy.workspace = true
bevy_widgetry_log = { path = "../log" }
bevy_widgetry_core = { path = "../core" }
bevy_widgetry_list_view = { path = "../list_view" }
bevy_widgetry_button = { path = "../button" }
bevy_widgetry_asset = { path = "../asset" }

[dev-dependencies]
bevy_widgetry_scroll_area = { path = "../scroll_area" }
bevy_widgetry_test_utils = { path = "../test_utils" }

[lints]
workspace = true

[[bench]]
name = "update"
harness = false
