[package]
name = "bevy_widgetry_file_dialog"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_widgetry_core = { path = "../core" }
bevy_widgetry_log = { path = "../log" }

[dev-dependencies]
bevy_widgetry_test_utils = { path = "../test_utils" }
proptest.workspace = true

[lints]
workspace = true

[[bench]]
name = "headless"
harness = false
