[package]
name = "bevy_widgetry_window"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_widgetry_asset = { path = "../asset" }
bevy_widgetry_core = { path = "../core" }

[dev-dependencies]
bevy_widgetry_test_utils = { path = "../test_utils" }

[lints]
workspace = true
